export const BANNER_LIST_LOADING = 'BANNER_LIST_LOADING';
export const BANNER_LIST_SUCCESS = 'BANNER_LIST_SUCCESS';
export const BANNER_LIST_ERROR = 'BANNER_LIST_ERROR';

export const BANNER_CREATE_LOADING = 'BANNER_CREATE_LOADING';
export const BANNER_CREATE_SUCCESS = 'BANNER_CREATE_SUCCESS';
export const BANNER_CREATE_ERROR = 'BANNER_CREATE_ERROR';

export const BANNER_EDIT_LOADING = 'BANNER_EDIT_LOADING';
export const BANNER_EDIT_SUCCESS = 'BANNER_EDIT_SUCCESS';
export const BANNER_EDIT_ERROR = 'BANNER_EDIT_ERROR';